### ISSUE TITLE
Неправильное использование поиска циклом проверок

### ISSUE THREAD

**Issue by egregors** [lamak/utmr#1]
https://github.com/lamak/utmr/blob/9031a19ad57f69ba2d0847d1b9cc563d5944d349/utmr/utmr.py#L162-L165

Ты опять зря проходишь весь массив. Либо, потенциально создаешь место для бага: если в коллекции несколько элементов, удовлетворяющих условию, ты получишь только последний. 

Выходи из цикла, как только нашел нужный объект, делая return внутри if

**Comment by lamak** [comment]
в данном случае мне нужен последний элемент

**Comment by egregors** [comment]
Да даже если так, почему бы тебе не сделать нечто такое:

```
for u in reversed(tree.findall('url')):
    if 'ReplyNATTN' in u.text: 
         return u.text
```
